### ISSUE TITLE
C++ PaintKit parses doesn't put "," at the end of lines

### ISSUE THREAD

**Issue by CredixYt** [michel-pi/csgo-items-parser#1]
Fix by changing `CppEnumHelper.cs:57` from `sb.AppendLine("\t" + BetterNaming(translation.Translation) + " = " + paintKit.Index.ToString());` to `sb.AppendLine("\t" + BetterNaming(translation.Translation) + " = " + paintKit.Index.ToString() + ",");`

@michel-pi 
EDIT: Fixed Markdown

**Comment by michel-pi** [comment]
thanks
